# Pandas Ödev 1

In [16]:
import pandas as pd
import numpy as np

1) İndexlerinde "Breaking Bad" , "Chernobyl" , "Leyla ile Mecnun" , "X-Men"  , "Captain America"  , "Disaster Movie" olan 
   Datasında 9.4 , 9.3 , 8.8 , 8.4 , 3.8 , 2.1 olan bir seri oluşturun.(2 Farklı yolla da oluşturun) (Datayı ve İndexleri liste olarak göndererek ve doğrudan dictionary göndererek.)


In [17]:
# 1. Yol
movie = ["Breaking Bad" , "Chernobyl" , "Leyla ile Mecnun" , "X-Men"  , "Captain America"  , "Disaster Movie"]
rating = [9.4 , 9.3 , 8.8 , 8.4 , 3.8 , 2.1]
seri_1 = pd.Series(data=rating, index=movie)
print("................Seri 1. Yol: ........................." , "\n", seri_1)

................Seri 1. Yol: ......................... 
 Breaking Bad        9.4
Chernobyl           9.3
Leyla ile Mecnun    8.8
X-Men               8.4
Captain America     3.8
Disaster Movie      2.1
dtype: float64


In [18]:
# 2. Yol
sozluk = {"Breaking Bad": 9.4 , "Chernobyl": 9.3 , "Leyla ile Mecnun": 8.8 , "X-Men": 8.4  , "Captain America": 3.8  , "Disaster Movie": 2.1}
seri_2= pd.Series(sozluk)
print("................Seri 2. Yol: ........................." , "\n", seri_2)

................Seri 2. Yol: ......................... 
 Breaking Bad        9.4
Chernobyl           9.3
Leyla ile Mecnun    8.8
X-Men               8.4
Captain America     3.8
Disaster Movie      2.1
dtype: float64


2) donem1_mat adında bir seri oluşturun. Bu serinin içinde "Ali" ,"Deniz" ,"Aslı" ,"Burak" ,"Kerem" ,"Yasemin" ,"Derya" index değerleri olsun, 
   85, 80 , 94 , 74 , 91 , 96 , 70 data değerleri olsun. Bu şekilde donem1 adında öğrencilerin 1.dönem matematik nor ortalamalarının tutulduğu bir seri oluşturun.

   donem2_mat adında başka bir seri oluşturun. Okula yeni bir öğrenci gelmiş olsun ve indexlerde bu sefer "Ali" ,"Deniz" ,"Aslı" ,"Burak" ,"Kerem" ,"Yasemin" ,"Derya" ,"Mert"         indexleri olsun. 80, 92 , 85 , 87, 90 , 92, 100, 83 ise dataları olsun. Bu iki seriyi birleştirerek bütün öğrencilerin yıl sonu matematik ORTALAMASINI hesaplayın.

   Not : Eğer bir öğrencinin sadece ikinci dönem notu bulunuyorsa, birinci dönem hesaba eklenmeden ikinci dönem notu yıl sonu notu olarak hesaplansın.


In [19]:
soz = { "Ali":85 ,"Deniz":80 ,"Aslı":94 ,"Burak":74 ,"Kerem":91 ,"Yasemin":96 ,"Derya":70}
soz_2 =  { "Ali":80 ,"Deniz":92 ,"Aslı":85 ,"Burak":87 ,"Kerem":90 ,"Yasemin":92 ,"Derya":100, "Mert":83}
donem1_mat = pd.Series(soz)
donem2_mat = pd.Series(soz_2)
ort = (donem1_mat + donem2_mat[:7]) / 2
ort.loc[donem2_mat.index[7]]= donem2_mat[7]
print(ort)


Ali        82.5
Deniz      86.0
Aslı       89.5
Burak      80.5
Kerem      90.5
Yasemin    94.0
Derya      85.0
Mert       83.0
dtype: float64


3) İndexlerinde "Osman", "Ozlem", "İnci", "Koray", "Melek" olan, columnlarında "Sınıf" , "Cinsiyet" , "Favori Ders" isimlerinde 3 column bulunan bir DF oluşturacaksınız. Osman'ın sınıfı 8 , cinsiyeti "E" , Favori Dersi "Fen"
Ozlem'in sınıfı 11 , cinsiyeti "K" , Favori Dersi "Mat"
İnci'nin sınıfı 5 , cinsiyeti "K" , Favori Dersi "Sosyal"
Koray'ın sınıfı 9 , cinsiyeti "E" , Favori Dersi "Mat"
Meleğin sınıfı 7 , cinsiyeti "K" , Favori Dersi "Ing"          Olacak şekilde bir df oluşturun.


In [20]:
indexs= ["Osman", "Ozlem", "İnci", "Koray", "Melek"]
data= {
    "Sınıf": [8,11,5,9,7] , 
    "Cinsiyet" : ["E", "K", "K", "E", "K"], 
    "Favori Ders": ["Fen", "Mat", "Sosyal", "Mat", "Ing"]
    }
df = pd.DataFrame(data= data, index= indexs)
df

Sınıf Cinsiyet Favori Ders
Osman      8        E         Fen
Ozlem     11        K         Mat
İnci       5        K      Sosyal
Koray      9        E         Mat
Melek      7        K         Ing

4) GitHubda bulunan "Advertising.csv" reklam datasını herhangi bir platformda DF olarak okuyun ve "df_adv" adında bir değişkene atayın. Ardından df_adv değişkeninin ilk 3 satırına, son 3 satırına , rastgele 3 satırına bakın.


In [21]:
df_adv = pd.read_csv("Advertising.csv")
print(df_adv.head(3), "\n", df_adv.tail(3), "\n", df_adv.sample(3))

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3 
         TV  radio  newspaper  sales
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4 
         TV  radio  newspaper  sales
135   48.3   47.0        8.5   11.6
141  193.7   35.4       75.6   19.2
77   120.5   28.5       14.2   14.2


5) Elde ettiğiniz "df_adv" infosuna ve describe'ına bakın ve yorumlamaya çalışın.

In [22]:
# İnfo
df_adv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


In [23]:
# describe
df_adv.describe()

TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

6) df_adv içinden sadece "TV" sütununu seri olarak çekin.


In [24]:
TV_series = pd.Series(df_adv["TV"])
TV_series

0      230.1
1       44.5
2       17.2
3      151.5
4      180.8
       ...  
195     38.2
196     94.2
197    177.0
198    283.6
199    232.1
Name: TV, Length: 200, dtype: float64

7) df_adv içinden "TV" ve "sales" sütununu çekin ve df_salesTV adında bir değişkene atayın.

In [25]:
df_salesTV = df_adv[["TV", "sales"]]
df_salesTV

TV  sales
0    230.1   22.1
1     44.5   10.4
2     17.2    9.3
3    151.5   18.5
4    180.8   12.9
..     ...    ...
195   38.2    7.6
196   94.2    9.7
197  177.0   12.8
198  283.6   25.5
199  232.1   13.4

[200 rows x 2 columns]

8) df_adv içindeki "TV" , "radio" , "newspaper" sütunlarındaki değerleri toplayarak "total_adv" adında yeni bir sütun oluşturun.

In [26]:
df_adv["total_adv"] = df_adv["TV"] + df_adv["newspaper"] + df_adv["radio"]
df_adv.head()

TV  radio  newspaper  sales  total_adv
0  230.1   37.8       69.2   22.1      337.1
1   44.5   39.3       45.1   10.4      128.9
2   17.2   45.9       69.3    9.3      132.4
3  151.5   41.3       58.5   18.5      251.3
4  180.8   10.8       58.4   12.9      250.0

9) df_adv içindeki "sales" sütununun drop edilmiş halini ekrana yazdırın. (Kalıcı hale getirmeyin. Sadece ekrana bastırın)


In [27]:
df_adv.drop("sales", axis=1)

TV  radio  newspaper  total_adv
0    230.1   37.8       69.2      337.1
1     44.5   39.3       45.1      128.9
2     17.2   45.9       69.3      132.4
3    151.5   41.3       58.5      251.3
4    180.8   10.8       58.4      250.0
..     ...    ...        ...        ...
195   38.2    3.7       13.8       55.7
196   94.2    4.9        8.1      107.2
197  177.0    9.3        6.4      192.7
198  283.6   42.0       66.2      391.8
199  232.1    8.6        8.7      249.4

[200 rows x 4 columns]

10) df_adv içindeki son 50 index'i(satırı) çekin ve ekrana yazdırın.


In [28]:
df_adv.tail(50)

TV  radio  newspaper  sales  total_adv
150  280.7   13.9       37.0   16.1      331.6
151  121.0    8.4       48.7   11.6      178.1
152  197.6   23.3       14.2   16.6      235.1
153  171.3   39.7       37.7   19.0      248.7
154  187.8   21.1        9.5   15.6      218.4
155    4.1   11.6        5.7    3.2       21.4
156   93.9   43.5       50.5   15.3      187.9
157  149.8    1.3       24.3   10.1      175.4
158   11.7   36.9       45.2    7.3       93.8
159  131.7   18.4       34.6   12.9      184.7
160  172.5   18.1       30.7   14.4      221.3
161   85.7   35.8       49.3   13.3      170.8
162  188.4   18.1       25.6   14.9      232.1
163  163.5   36.8        7.4   18.0      207.7
164  117.2   14.7        5.4   11.9      137.3
165  234.5    3.4       84.8   11.9      322.7
166   17.9   37.6       21.6    8.0       77.1
167  206.8    5.2       19.4   12.2      231.4
168  215.4   23.6       57.6   17.1      296.6
169  284.3   10.6        6.4   15.0      301.3
170   50.0   11.6       18.4    8.4       80.0
171  164.5   20.9       47.4   14.5      232.8
172   19.6   20.1       17.0    7.6       56.7
173  168.4    7.1       12.8   11.7      188.3
174  222.4    3.4       13.1   11.5      238.9
175  276.9   48.9       41.8   27.0      367.6
176  248.4   30.2       20.3   20.2      298.9
177  170.2    7.8       35.2   11.7      213.2
178  276.7    2.3       23.7   11.8      302.7
179  165.6   10.0       17.6   12.6      193.2
180  156.6    2.6        8.3   10.5      167.5
181  218.5    5.4       27.4   12.2      251.3
182   56.2    5.7       29.7    8.7       91.6
183  287.6   43.0       71.8   26.2      402.4
184  253.8   21.3       30.0   17.6      305.1
185  205.0   45.1       19.6   22.6      269.7
186  139.5    2.1       26.6   10.3      168.2
187  191.1   28.7       18.2   17.3      238.0
188  286.0   13.9        3.7   15.9      303.6
189   18.7   12.1       23.4    6.7       54.2
190   39.5   41.1        5.8   10.8       86.4
191   75.5   10.8        6.0    9.9       92.3
192   17.2    4.1       31.6    5.9       52.9
193  166.8   42.0        3.6   19.6      212.4
194  149.7   35.6        6.0   17.3      191.3
195   38.2    3.7       13.8    7.6       55.7
196   94.2    4.9        8.1    9.7      107.2
197  177.0    9.3        6.4   12.8      192.7
198  283.6   42.0       66.2   25.5      391.8
199  232.1    8.6        8.7   13.4      249.4

11) df_adv içinde satışları 25'den fazla olanları getirin.

In [29]:
df_adv[df_adv["sales"] > 25]

TV  radio  newspaper  sales  total_adv
36   266.9   43.8        5.0   25.4      315.7
98   289.7   42.3       51.2   25.4      383.2
147  243.2   49.0       44.3   25.4      336.5
175  276.9   48.9       41.8   27.0      367.6
183  287.6   43.0       71.8   26.2      402.4
198  283.6   42.0       66.2   25.5      391.8

12) df_adv içinde "TV" reklamlarına 250'den fazla VE "newspaper" reklamlarına 60'dan fazla harcama yapanları getirin.


In [30]:
df_adv[(df_adv["TV"] > 250) & (df_adv["newspaper"]>60)]

TV  radio  newspaper  sales  total_adv
93   250.9   36.5       72.3   22.2      359.7
101  296.4   36.3      100.9   23.8      433.6
183  287.6   43.0       71.8   26.2      402.4
198  283.6   42.0       66.2   25.5      391.8

13) df_adv içinde "newspaper" reklam harcamaları 70'den fazla VEYA "radio" reklam harcamaları 50'den fazla olanları getirin.


In [32]:
df_adv[(df_adv["radio"] > 50) | (df_adv["newspaper"]> 70)]

TV  radio  newspaper  sales  total_adv
5      8.7   48.9       75.0    7.2      132.6
16    67.8   36.6      114.0   12.5      218.4
75    16.9   43.7       89.4    8.7      150.0
88    88.3   25.5       73.4   12.9      187.2
93   250.9   36.5       72.3   22.2      359.7
101  296.4   36.3      100.9   23.8      433.6
118  125.7   36.9       79.2   15.9      241.8
124  229.5   32.3       74.2   19.7      336.0
141  193.7   35.4       75.6   19.2      304.7
165  234.5    3.4       84.8   11.9      322.7
183  287.6   43.0       71.8   26.2      402.4

14) df_adv içinde "sales" ları 10 ile 15(10 ve 15 dahil) arasında olanları getirin.


In [35]:
df_adv[(df_adv["sales"] >= 10) & (df_adv["sales"] <= 15)].sort_values(by="sales")

TV  radio  newspaper  sales  total_adv
157  149.8    1.3       24.3   10.1      175.4
149   44.7   25.8       20.6   10.1       91.1
38    43.1   26.7       35.1   10.1      104.9
145  140.3    1.9        9.0   10.3      151.2
186  139.5    2.1       26.6   10.3      168.2
..     ...    ...        ...    ...        ...
102  280.2   10.1       21.4   14.8      311.7
45   175.1   22.5       31.5   14.9      229.1
162  188.4   18.1       25.6   14.9      232.1
26   142.9   29.3       12.6   15.0      184.8
169  284.3   10.6        6.4   15.0      301.3

[80 rows x 5 columns]

15) df_adv içinde "sales" ları tam olarak 18.3 veya 14.0 veya 25.5 veya 21.7 veya 13.6 veya 6.9 olanları getirin.


In [39]:
df_adv[(df_adv["sales"] == 18.3) | (df_adv["sales"] == 14.0) | (df_adv["sales"] == 25.5) | (df_adv["sales"] == 21.7) | (df_adv["sales"] == 13.6) | (df_adv["sales"] == 6.9)]

TV  radio  newspaper  sales  total_adv
63   102.7   29.6        8.4   14.0      140.7
70   199.1   30.6       38.7   18.3      268.4
76    27.5    1.6       20.7    6.9       49.8
83    68.4   44.5       35.6   13.6      148.5
84   213.5   43.0       33.8   21.7      290.3
198  283.6   42.0       66.2   25.5      391.8

16) GitHubda bulunan "tips.csv" restoran datasını "df_tips" adıyla okuyun. Ardından ilk 5 satırına bakın.


In [40]:
df_tips = pd.read_csv("tips.csv")
df_tips.head(5)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251

17) df_tips'in "CC Number" ve "Payment ID" column'larını kalıcı olarak düşürün.


In [43]:
df_tips.drop(["CC Number" , "Payment ID"], inplace=True, axis=1)

In [44]:
df_tips

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name  
0    Christy Cunningham  
1        Douglas Tucker  
2        Travis Walters  
3      Nathaniel Harris  
4          Tonya Carter  
..                  ...  
239       Michael Avila  
240      Monica Sanders  
241          Keith Wong  
242        Dennis Dixon  
243     Michelle Hardin  

[244 rows x 9 columns]

18) df_tips'in "Payer Name" column'unu kalıcı olarak index yapın ve artık columndan düşürün.

In [45]:
df_tips.set_index("Payer Name", drop=True, inplace=True)

In [46]:
df_tips

total_bill   tip     sex smoker   day    time  size  \
Payer Name                                                                
Christy Cunningham       16.99  1.01  Female     No   Sun  Dinner     2   
Douglas Tucker           10.34  1.66    Male     No   Sun  Dinner     3   
Travis Walters           21.01  3.50    Male     No   Sun  Dinner     3   
Nathaniel Harris         23.68  3.31    Male     No   Sun  Dinner     2   
Tonya Carter             24.59  3.61  Female     No   Sun  Dinner     4   
...                        ...   ...     ...    ...   ...     ...   ...   
Michael Avila            29.03  5.92    Male     No   Sat  Dinner     3   
Monica Sanders           27.18  2.00  Female    Yes   Sat  Dinner     2   
Keith Wong               22.67  2.00    Male    Yes   Sat  Dinner     2   
Dennis Dixon             17.82  1.75    Male     No   Sat  Dinner     2   
Michelle Hardin          18.78  3.00  Female     No  Thur  Dinner     2   

                    price_per_person  
Payer Name                            
Christy Cunningham              8.49  
Douglas Tucker                  3.45  
Travis Walters                  7.00  
Nathaniel Harris               11.84  
Tonya Carter                    6.15  
...                              ...  
Michael Avila                   9.68  
Monica Sanders                 13.59  
Keith Wong                     11.34  
Dennis Dixon                    8.91  
Michelle Hardin                 9.39  

[244 rows x 8 columns]

19) df_tips içindeki kayıtlardan kişi sayısı 4 veya 4'den fazla olan siparişlerin kaç tane olduğunu bulun.(Sorguyu yazıp istediğimiz satırları getirdikten sonra basitçe len() fonksiyonunu kullanarak sayılarını bulabilirsiniz. Veya daha güzeli .shape[0] yaparak elde ettiğiniz sorguda kaç satır olduğunun sayısına ulaşabilirsiniz.)


In [49]:
df_tips[df_tips["size"] >= 4].shape[0]

46

20) df_tips içindeki Kişi sayısı 2 ya da 3 olan, sigara içen, erkek olan ve ödediği ücret 20 dolardan az olan kişi sayısını bulalım.

In [50]:
df_tips[((df_tips["size"] == 2) | (df_tips["size"] == 3)) & (df_tips["smoker"]== "Yes") & (df_tips["total_bill"] < 20.0)]

total_bill   tip     sex smoker   day    time  size  \
Payer Name                                                               
Troy Guerrero           11.24  1.76    Male    Yes   Sat  Dinner     2   
Ryan Hernandez          13.81  2.00    Male    Yes   Sat  Dinner     2   
Joseph Hart             11.02  1.98    Male    Yes   Sat  Dinner     2   
Adam Hall               15.01  2.09    Male    Yes   Sat  Dinner     2   
Mark Smith              17.92  3.08    Male    Yes   Sat  Dinner     2   
Louis Torres            19.44  3.00    Male    Yes  Thur   Lunch     2   
Leah Ramirez             5.75  1.00  Female    Yes   Fri  Dinner     2   
Natalie Nguyen          16.32  4.30  Female    Yes   Fri  Dinner     2   
Eric Herrera            12.03  1.50    Male    Yes   Fri  Dinner     2   
Lori Lynch              11.35  2.50  Female    Yes   Fri  Dinner     2   
Tiffany Colon           15.38  3.00  Female    Yes   Fri  Dinner     2   
David Price             15.36  1.64    Male    Yes   Sat  Dinner     2   
Amanda Anderson         14.31  4.00  Female    Yes   Sat  Dinner     2   
Jason Burgess           16.00  2.00    Male    Yes  Thur   Lunch     2   
Audrey Griffin          17.51  3.00  Female    Yes   Sun  Dinner     2   
Sara Jimenez            10.59  1.61  Female    Yes   Sat  Dinner     2   
Amy Hill                10.63  2.00  Female    Yes   Sat  Dinner     2   
David Hall              15.81  3.16    Male    Yes   Sat  Dinner     2   
Larry White              7.25  5.15    Male    Yes   Sun  Dinner     2   
Brian Miles             16.82  4.00    Male    Yes   Sun  Dinner     2   
Walter Simmons          17.89  2.00    Male    Yes   Sun  Dinner     2   
John Dudley             14.48  2.00    Male    Yes   Sun  Dinner     2   
Melanie Gray             9.60  4.00  Female    Yes   Sun  Dinner     2   
Glenda Wiggins          18.15  3.50  Female    Yes   Sun  Dinner     3   
Riley Barnes            15.69  1.50    Male    Yes   Sun  Dinner     2   
Kristy Boyd             19.81  4.19  Female    Yes  Thur   Lunch     2   
Raymond Sullivan        15.48  2.02    Male    Yes  Thur   Lunch     2   
Benjamin Weber          16.58  4.00    Male    Yes  Thur   Lunch     2   
Eric Martin             10.34  2.00    Male    Yes  Thur   Lunch     2   
Katherine Bond          13.00  2.00  Female    Yes  Thur   Lunch     2   
Joseph Murphy MD        13.51  2.00    Male    Yes  Thur   Lunch     2   
Jason Conrad            18.71  4.00    Male    Yes  Thur   Lunch     3   
Abigail Parks           12.74  2.01  Female    Yes  Thur   Lunch     2   
Ashley Shaw             13.00  2.00  Female    Yes  Thur   Lunch     2   
Toni Brooks             16.40  2.50  Female    Yes  Thur   Lunch     2   
Carly Reyes             16.47  3.23  Female    Yes  Thur   Lunch     3   
Sarah Cunningham        12.76  2.23  Female    Yes   Sat  Dinner     2   
Robin Andersen          13.27  2.50  Female    Yes   Sat  Dinner     2   
Jessica Owen            12.90  1.10  Female    Yes   Sat  Dinner     2   
Gary Orr                11.59  1.50    Male    Yes   Sat  Dinner     2   
Nicholas Archer          7.74  1.44    Male    Yes   Sat  Dinner     2   
Ricky Johnson           12.16  2.20    Male    Yes   Fri   Lunch     2   
Leslie Kaufman          13.42  3.48  Female    Yes   Fri   Lunch     2   
Ronald Vaughn DVM       13.42  1.58    Male    Yes   Fri   Lunch     2   
Whitney Arnold          16.27  2.50  Female    Yes   Fri   Lunch     2   
Ruth Weiss              10.09  2.00  Female    Yes   Fri   Lunch     2   
Jason Parks             15.69  3.00    Male    Yes   Sat  Dinner     3   
Tracy Douglas           15.53  3.00    Male    Yes   Sat  Dinner     2   
Matthew Myers           12.60  1.00    Male    Yes   Sat  Dinner     2   

                   price_per_person  
Payer Name                           
Troy Guerrero                  5.62  
Ryan Hernandez                 6.90  
Joseph Hart                    5.51  
Adam Hall                      7.50  
Mark Smith      